# Generated by Django 5.1.2 on 2025-11-20 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Priority',
            new_name='priority',
        ),
    ]
