# Generated by Django 5.1.2 on 2025-11-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=199)),
                ('description', models.TextField(blank=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('param1', models.CharField(blank=True, max_length=100)),
                ('param2', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=13, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='core.project')),
            ],
            options={
                'ordering': ['category', 'model'],
            },
        ),
    ]
